steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "europe-west12-docker.pkg.dev/pascal2026/pascal/${_SERVICE_NAME}:${SHORT_SHA}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west12-docker.pkg.dev/pascal2026/pascal/${_SERVICE_NAME}:${SHORT_SHA}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "europe-west12-docker.pkg.dev/pascal2026/pascal/${_SERVICE_NAME}:${SHORT_SHA}",
        "--region",
        "europe-west12",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
options:
  logging: CLOUD_LOGGING_ONLY